version: "3.8"

services:
    {{cookiecutter.app_name}}:
        build: {{cookiecutter.app_name}}/
        ports:
            - 127.0.0.1:{{cookiecutter.app_port}}:{{cookiecutter.app_port}}
    db:
        image: postgres:14-alpine
        ports:
            - 127.0.0.1:5432:5432
        environment:
            POSTGRES_PASSWORD: localdev
        volumes:
            - db-data:/var/lib/postgres/data
            - ./database/initdb:/docker-entrypoint-initdb.d/
    nginx:
        image: nginx:1.22.0
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:443:443
        volumes:
            - ./nginx/www:/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    redis:
        image: redis:7.0.0
        ports:
            - 127.0.0.1:6379:6379
    rabbitmq:
        image: rabbitmq:3.10.2
        ports:
            - 127.0.0.1:4369:4369
            - 127.0.0.1:5672:5672
            - 127.0.0.1:25672:25672
            - 127.0.0.1:15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
    flower:
        image: mher/flower:0.9.7
        ports:
            - 127.0.0.1:5555:5555
        environment:
            CELERY_BROKER_URL: "ampq://guest:guest@rabbitmq//"
            CELERY_RESULT_BACKEND: redis://redis:6379/7
    localstack:
        image: localstack/localstack:latest
        ports:
            - 127.0.0.1:4566:4566
            - 127.0.0.1:4510-4559:4510-4559
        environment:
            LOCALSTACK_SERVICES: s3
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
        ports:
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
volumes:
    db-data:
    elasticsearch-data:
